### PR TITLE
fix(web): logging if no domain is entered

### LINKED ISSUE #1036: 我在外网服务器使用, 网页打开，里面没有任何服务商选项
### 问题描述

我在外网服务器使用, 网页打开，里面没有任何服务商选项
微信截图_20240310165800

### DNS服务商

腾讯云

### 是否已搜索同类问题

未搜索

### 操作系统

Windows

### 架构

x86_64

### 版本

最新版本ddns-go 6.2

### 安装方式

其它

### 额外信息

_No response_

### PR DESCRIPTION
**Pull request by WaterLemons2k**
# What does this PR do?

Logging when both IPv4 and IPv6 domains are not provided.

Fixes #1036 and other similar issues.

# Motivation

Currently, if both IPv4 and IPv6 domains are not provided, nothing happens. In this case, we should log this.

- #899
- #1036

# Additional Notes

Bool `firstTime` was based on a config error, but the error was ignored. Fixed.

### CODE REVIEW

**Comment by jeessy2** [comment]
When IPv4 and IPv6 domains are not filled in, only display logs instead of throwing exceptions

File: web/save.go [hunk 1]
```diff
@@ -107,27 +106,29 @@ func checkAndSave(request *http.Request) string {
...
 		dnsConf.Ipv4.URL = strings.TrimSpace(v.Ipv4Url)
 		dnsConf.Ipv4.NetInterface = v.Ipv4NetInterface
 		dnsConf.Ipv4.Cmd = strings.TrimSpace(v.Ipv4Cmd)
-		if strings.Contains(v.Ipv4Domains, "\r\n") {
-			dnsConf.Ipv4.Domains = strings.Split(v.Ipv4Domains, "\r\n")
-		} else {
-			dnsConf.Ipv4.Domains = strings.Split(v.Ipv4Domains, "\n")
+		dnsConf.Ipv4.Domains = splitLines(v.Ipv4Domains)
+
+		if v.Ipv6Enable && v.Ipv6Domains == "" {
```
Comment (jeessy2) [inline web/save.go:121]: ```if v.Ipv4Domains == "" && v.Ipv6Domains == "" {...}``` Because it is enabled by default, this can reduce unnecessary prompts

Comment (WaterLemons2k) [reply web/save.go]: > `if v.Ipv4Domains == "" && v.Ipv6Domains == "" {...}` Because it is enabled by default, this can reduce unnecessary prompts

Yes, we should only deal with first time configuration.

File: web/save.go [hunk 2]
```diff
@@ -107,27 +106,25 @@ func checkAndSave(request *http.Request) string {
 		dnsConf.DNS.Name = v.DnsName
 		dnsConf.DNS.ID = strings.TrimSpace(v.DnsID)
 		dnsConf.DNS.Secret = strings.TrimSpace(v.DnsSecret)
+
+		if v.Ipv4Domains == "" && v.Ipv6Domains == "" {
+			util.Log("请输入至少一个域名")
```
Comment (jeessy2) [inline web/save.go:111]: `第 {} 个配置未填写域名`？

Comment (WaterLemons2k) [reply web/save.go]: Added. Maybe we need to deal with ordinal numbers in English?

Comment (jeessy2) [reply web/save.go]: It's okay

**Review by jeessy2 — APPROVED** [review]
thanks
